services:
  # TODO: PostgreSQL
  postgres:
    image: postgres:18
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mlsec
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql
      - ./services/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - backend_net

  # Test database 
  postgres-test:
    image: postgres:18
    container_name: test-postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: mlsec_test
    ports:
      - "5433:5432"
    volumes:
      - pgdata_test:/var/lib/postgresql
      - ./services/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - backend_net

  minio:
    image: minio/minio:latest
    container_name: mlsec-minio
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"  # API
      - "9001:9001"  # Console UI
    volumes:
      - miniodata:/data
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - backend_net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: mlsec
      RABBITMQ_DEFAULT_PASS: mlsec
    ports:
      - "5672:5672" # AMQP
      - "15672:15672" # Management UI
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    networks:
      - backend_net

  # TODO: FastAPI
  api:
    build:
      context: ./services/api
      dockerfile: Dockerfile
    container_name: mlsec-api
    environment:
      DATABASE_URL: postgresql://postgres:password123@postgres:5432/mlsec
      CELERY_BROKER_URL: amqp://mlsec:mlsec@rabbitmq:5672//
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_SECURE: "false"
    ports:
      - "8000:8000"
    networks:
      - backend_net
    depends_on:
      - postgres
      - rabbitmq
      - minio

  # Gateway to control traffic for student containers
  eval-gateway:
    build:
      context: ./services/gateway
      dockerfile: Dockerfile
    container_name: mlsec-gateway
    environment:
      GATEWAY_SECRET: welovemarcus
    ports:
      - "8080:8080"
    networks:
      - backend_net

  # Placeholder worker container (Celery wiring added in a later step. Unless we want to have persistent workers?)
  worker:
    build:
      context: ./services/worker
      dockerfile: Dockerfile
    container_name: mlsec-worker
    environment:
      DATABASE_URL: postgresql://postgres:password123@postgres:5432/mlsec
      CELERY_BROKER_URL: amqp://mlsec:mlsec@rabbitmq:5672//
      CELERY_DEFAULT_QUEUE: mlsec
      API_WS_URL: ws://host.docker.internal:8765/ws/eval/samples # Temporary WebSocket to Simulate FastAPI
      GATEWAY_SECRET: welovemarcus
      GATEWAY_URL: http://mlsec-gateway:8080
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_ROOT_PASSWORD:-minioadmin}
      MINIO_SECURE: "false"
    extra_hosts:
      - "host.docker.internal:host-gateway" # Also Temporary for WebSocket Simulation
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.yaml:/app/config.yaml:ro
    group_add:
      - "${DOCKER_GID:-999}" # Allows Worker container to interact with Docker Engine
    networks:
      - backend_net
    depends_on:
      - postgres
      - rabbitmq
      - minio

  # Frontend (Astro)
  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile
    container_name: mlsec-frontend
    environment:
      PUBLIC_API_URL: http://localhost:8000
    volumes:
      - ./services/frontend:/app
      - /app/node_modules
    ports:
      - "4321:4321"
    networks:
      - backend_net
    depends_on:
      - api
  # TODO: Adminer (Nice to have, not necessary)
  # adminer:


networks:
  # TODO: Secure communication network for evaluation end.
  backend_net:
    name: backend_net
    driver: bridge
volumes:
  # TODO: Establish volumes for postgres, minio, rabbitmq
  pgdata:
  pgdata_test:
  rabbitmqdata:
  miniodata:


